from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(30, 220, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.btnDivide = QtWidgets.QPushButton(self.centralwidget)
        self.btnDivide.setGeometry(QtCore.QRect(330, 220, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnDivide.setFont(font)
        self.btnDivide.setObjectName("btnDivide")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(230, 220, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn9.setFont(font)
        self.btn9.setObjectName("btn9")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(130, 220, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn8.setFont(font)
        self.btn8.setObjectName("btn8")
        self.btnMultiply = QtWidgets.QPushButton(self.centralwidget)
        self.btnMultiply.setGeometry(QtCore.QRect(330, 310, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnMultiply.setFont(font)
        self.btnMultiply.setObjectName("btnMultiply")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(30, 310, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(130, 310, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn5.setFont(font)
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(230, 310, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn6.setFont(font)
        self.btn6.setObjectName("btn6")
        self.btnSubtract = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubtract.setGeometry(QtCore.QRect(330, 400, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSubtract.setFont(font)
        self.btnSubtract.setObjectName("btnSubtract")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(30, 400, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(130, 400, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(230, 400, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(330, 490, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(30, 490, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn0.setFont(font)
        self.btn0.setObjectName("btn0")
        self.btnPoint = QtWidgets.QPushButton(self.centralwidget)
        self.btnPoint.setGeometry(QtCore.QRect(130, 490, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnPoint.setFont(font)
        self.btnPoint.setObjectName("Point")
        self.btnEquals = QtWidgets.QPushButton(self.centralwidget)
        self.btnEquals.setGeometry(QtCore.QRect(230, 490, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnEquals.setFont(font)
        self.btnEquals.setObjectName("btnEquals")
        self.resultLine = QtWidgets.QLineEdit(self.centralwidget)
# So you can't type into it
        self.resultLine.setReadOnly(True)
        self.resultLine.setGeometry(QtCore.QRect(30, 75, 291, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.resultLine.setFont(font)
        self.resultLine.setObjectName("resultLine")
        self.btnC = QtWidgets.QPushButton(self.centralwidget)
        self.btnC.setGeometry(QtCore.QRect(330, 30, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnC.setFont(font)
        self.btnC.setObjectName("btnC")
        self.insertDataLine = QtWidgets.QLineEdit(self.centralwidget)
# So you can't type into it
        self.insertDataLine.setReadOnly(True)
        self.insertDataLine.setGeometry(QtCore.QRect(30, 30, 291, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.insertDataLine.setFont(font)
        self.insertDataLine.setObjectName("insertDataLine")
        self.btnOpenBracket = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenBracket.setGeometry(QtCore.QRect(30, 130, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnOpenBracket.setFont(font)
        self.btnOpenBracket.setObjectName("btnOpenBracket")
        self.btnSquare = QtWidgets.QPushButton(self.centralwidget)
        self.btnSquare.setGeometry(QtCore.QRect(230, 130, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnSquare.setFont(font)
        self.btnSquare.setObjectName("btnSquare")
        self.btnCloseBracket = QtWidgets.QPushButton(self.centralwidget)
        self.btnCloseBracket.setGeometry(QtCore.QRect(130, 130, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCloseBracket.setFont(font)
        self.btnCloseBracket.setObjectName("btnCloseBracket")
        self.btnRoot = QtWidgets.QPushButton(self.centralwidget)
        self.btnRoot.setGeometry(QtCore.QRect(330, 130, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnRoot.setFont(font)
        self.btnRoot.setObjectName("btnRoot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 448, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn0.clicked.connect(self.add0)
        self.btn1.clicked.connect(self.add1)
        self.btn2.clicked.connect(self.add2)
        self.btn3.clicked.connect(self.add3)
        self.btn4.clicked.connect(self.add4)
        self.btn5.clicked.connect(self.add5)
        self.btn6.clicked.connect(self.add6)
        self.btn7.clicked.connect(self.add7)
        self.btn8.clicked.connect(self.add8)
        self.btn9.clicked.connect(self.add9)
        self.btnAdd.clicked.connect(self.addAdd)
        self.btnSubtract.clicked.connect(self.addSub)
        self.btnMultiply.clicked.connect(self.addMultiply)
        self.btnDivide.clicked.connect(self.addDivide)
        self.btnOpenBracket.clicked.connect(self.addOpenBracket)
        self.btnCloseBracket.clicked.connect(self.addCloseBracket)
        self.btnSquare.clicked.connect(self.addSquare)
        self.btnRoot.clicked.connect(self.addRoot)
        self.btnPoint.clicked.connect(self.addPoint)
        self.btnC.clicked.connect(self.addC)
        self.btnEquals.clicked.connect(self.addRes)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btnDivide.setText(_translate("MainWindow", "/"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btnMultiply.setText(_translate("MainWindow", "*"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btnSubtract.setText(_translate("MainWindow", "-"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btnAdd.setText(_translate("MainWindow", "+"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btnPoint.setText(_translate("MainWindow", ","))
        self.btnEquals.setText(_translate("MainWindow", "="))
        self.btnC.setText(_translate("MainWindow", "C"))
        self.btnOpenBracket.setText(_translate("MainWindow", "("))
        self.btnSquare.setText(_translate("MainWindow", "²"))
        self.btnCloseBracket.setText(_translate("MainWindow", ")"))
        self.btnRoot.setText(_translate("MainWindow", "√"))

    add0 = lambda self: self.insertDataLine.insert('0')

    add1 = lambda self: self.insertDataLine.insert('1')

    add2 = lambda self: self.insertDataLine.insert('2')

    add3 = lambda self: self.insertDataLine.insert('3')

    add4 = lambda self: self.insertDataLine.insert('4')

    add5 = lambda self: self.insertDataLine.insert('5')

    add6 = lambda self: self.insertDataLine.insert('6')

    add7 = lambda self: self.insertDataLine.insert('7')
        
    add8 = lambda self: self.insertDataLine.insert('8')
        
    add9 = lambda self: self.insertDataLine.insert('9')
        
    addAdd = lambda self: self.insertDataLine.insert('+')
        
    addSub = lambda self: self.insertDataLine.insert('-')
        
    addMultiply = lambda self: self.insertDataLine.insert('*')
        
    addDivide = lambda self: self.insertDataLine.insert('/')
        
    addOpenBracket = lambda self: self.insertDataLine.insert('(')
        
    addCloseBracket = lambda self: self.insertDataLine.insert(')')
        
    addPoint = lambda self: self.insertDataLine.insert('.')

    def addC(self):
        self.insertDataLine.clear()
        self.resultLine.clear()

    def addRes(self):
        self.resultLine.clear()
        a = self.insertDataLine.text()
        b = eval(str(a))
        self.resultLine.insert(str(b))

    def addSquare(self):
        a = self.insertDataLine.text()
        b = pow(float(eval(a)), 2)
        self.insertDataLine.clear()
        self.insertDataLine.insert(str(b))

    def addRoot(self):
        import math
        a = self.insertDataLine.text()
        b = math.sqrt(float(eval(a)))
        self.insertDataLine.clear()
        self.insertDataLine.insert(str(b))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
